In [ ]:
# TODO TASK
# Problem - 1: Array Creation:
# 1
import numpy as np

array = np.empty((2, 2))
print(array)


[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]


In [ ]:
# 2

import numpy as np

array = np.ones((4, 2))
print(array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
# 3

import numpy as np

shape = (3, 2)
fill_value = 13

array = np.full(shape, fill_value)
print(array)


[[13 13]
 [13 13]
 [13 13]]


In [ ]:
# 4

import numpy as np

array = np.zeros_like(np.full((3,2), 13))
print(array)

[[0 0]
 [0 0]]


In [ ]:
# 5

import numpy as np

array = np.ones_like(np.full((3,2), 13))
print(array)

[[1 1]
 [1 1]
 [1 1]]


In [ ]:
# 6
import numpy as np

new_list = [1, 2, 3, 4]

array = np.array(new_list)
print(array)

[1 2 3 4]


In [ ]:
# 4.1.1 Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
# 1
import numpy as np

array = np.arange(10, 50) # arange from 10 to 49 (inclusive)
print(array)



[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# 2
import numpy as np

array = np.arange(9) # arange from 0 to 8 inclusive

matrix = array.reshape(3, 3) # reshaoping it into 3x3 matrix

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# 3
import numpy as np

identity_matrix = np.eye(3, dtype=int) # 3x3 identity matrix
print(identity_matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
# 4
import numpy as np

random_array = np.random.random(30) # random array of size 30

mean = np.mean(random_array) # finding its mean

print("random array:\n", random_array)
print()
print("mean of the arrray: ", mean)

random array:
 [0.76939879 0.36415335 0.7335724  0.46720219 0.42321634 0.26752839
 0.73624092 0.68094586 0.6573512  0.5547441  0.71786855 0.02070482
 0.10295535 0.03212821 0.07418739 0.77051512 0.30314796 0.31013227
 0.80291258 0.32131886 0.2138324  0.77315328 0.57268315 0.33715994
 0.94812205 0.45244721 0.97334768 0.48699449 0.98969916 0.5743236 ]

mean of the arrray:  0.5143995870312873


In [ ]:
# 5
import numpy as np

random_array = np.random.random((10, 10)) # 10X10 array with random values

# calaculating its minimum and maximum values
minimum_value = random_array.min()
maximum_value = random_array.max()

print("Random 10x10 Array:\n", random_array)
print()
print("min value = ", minimum_value)
print("max value = ", maximum_value)

Random 10x10 Array:
 [[0.79575063 0.03127989 0.36373958 0.2732173  0.459179   0.89634417
  0.29792379 0.47652746 0.22433227 0.10139611]
 [0.85661729 0.68746967 0.6773845  0.94185831 0.0918785  0.88499705
  0.31657423 0.8165066  0.74232973 0.28232002]
 [0.90335766 0.98830161 0.21495514 0.43126758 0.46712791 0.84743317
  0.38138657 0.34534465 0.85797068 0.46355746]
 [0.12096979 0.1180624  0.74893955 0.66560245 0.38758497 0.81217114
  0.73811352 0.17824455 0.27742973 0.99209107]
 [0.72629472 0.76017591 0.56515727 0.79234315 0.87594456 0.12671784
  0.19971961 0.510554   0.2989199  0.13341296]
 [0.01931711 0.66642171 0.92853608 0.34208703 0.93389138 0.15455974
  0.01139937 0.8995841  0.50773383 0.50548467]
 [0.94450738 0.63641845 0.6465516  0.5114555  0.90063451 0.48319963
  0.63857963 0.04984683 0.04762529 0.87467554]
 [0.65631285 0.0627208  0.03796535 0.2837882  0.1282312  0.77198014
  0.51448132 0.29854303 0.95870905 0.71809341]
 [0.37190289 0.07091833 0.72402158 0.23452332 0.41882956 0.

In [ ]:
# 6
import numpy as np

array = np.zeros(10) # zero array of size 10

array[4] = 1 # replacing the 5th item(4 index) with 1

print(array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
# 7
import numpy as np

array = np.array([1, 2, 0, 0, 4, 0])
reverse_array = array[::-1]  # Reverse the array using slicing

print(reverse_array)

[0 4 0 0 2 1]


In [ ]:
# 8

arr = np.zeros((4, 4), dtype = int) # creating a 5x5 matrix with zeros in it


arr[0, :] = 1 # keeping the first and the last row as 1
arr[-1, :] = 1


# keeping the first and the last column as 1
arr[:, 0] = 1
arr[:, -1] = 1


print(arr)

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


In [ ]:
# 9
import numpy as np

# Creating an 8x8 matrix
checkerboard = np.zeros((8, 8), dtype=int)

checkerboard[::2, ::2] = 1  # selects the even rows and column
checkerboard[1::2, 1::2] = 1  # selects the odd rows and column

print(checkerboard)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [ ]:
# Problem - 3: Array Operations:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1
sum = x + y
print("Sum of x and y:")
print(sum)

# 2
difference = x - y
print("\nDifference of x and y:")
print(difference)

# 3
multiplied_with_5 = y * 5
print("\y Multiplied by 5:")
print(multiplied_with_5)

# 4
square_x = np.square(x)
print("\nSquare of each element in x:")
print(square_x)

square_y = np.square(y)
print("\nSquare of each element in y:")
print(square_y)

# 5
dot_product_of_vw = np.dot(v, w)
print("\nDot product of v and w:")
print(dot_product_of_vw)

dot_product_of_xv = np.dot(x, v)
print("\nDot product of x and v:")
print(dot_product_of_xv)

dot_product_of_xy = np.dot(x, y)
print("\nDot product of x and y:")
print(dot_product_of_xy)


# 6
concatenate_xy = np.concatenate((x, y), axis=1)
print("\nConcatenated x and y along rows:")
print(concatenate_xy)


# 7
concat_vw = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)
print("Concatenated v and w along columns:")
print(concat_vw)


# concat_xv = np.concatenate((x, v), axis=1)
# ValueError: all the input arrays must have same number of dimensions


Sum of x and y:
[[ 6  8]
 [10 13]]

Difference of x and y:
[[-4 -4]
 [-4 -3]]
\y Multiplied by 5:
[[25 30]
 [35 40]]

Square of each element in x:
[[ 1  4]
 [ 9 25]]

Square of each element in y:
[[25 36]
 [49 64]]

Dot product of v and w:
219

Dot product of x and v:
[29 77]

Dot product of x and y:
[[19 22]
 [50 58]]

Concatenated x and y along rows:
[[1 2 5 6]
 [3 5 7 8]]
Concatenated v and w along columns:
[[ 9 11]
 [10 12]]


In [ ]:
# Problem - 4: Matrix Operations:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1 Prove A * A_inv = I
A_inverse = np.linalg.inv(A)
result = np.dot(A, A_inverse)
result = np.array(result, dtype=int)

print("A * A_inv = \n", result)
print()

# 2 Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB = \n", AB)
print()
print("BA = \n", BA)
print()


# 3. Prove (AB)^T = B^T * A^T
transpose_of_AB = np.transpose(AB)
transpose_of_B_x_transpose_of_A = np.dot(np.transpose(B), np.transpose(A))
print("(AB)^T = \n", transpose_of_AB)
print()
print("B^T * A^T = \n", transpose_of_B_x_transpose_of_A)
print()


A * A_inv = 
 [[1 0]
 [0 0]]

AB = 
 [[23 13]
 [51 29]]

BA = 
 [[36 44]
 [13 16]]

(AB)^T = 
 [[23 51]
 [13 29]]

B^T * A^T = 
 [[23 51]
 [13 29]]

Therefore X = [ 2.  1. -2.]


In [ ]:
# Solve the system of equations using inverse method
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])
X = []
if(np.linalg.det(A) != 0):

    A_inverse = np.linalg.inv(A)
    X = np.dot(A_inverse, B)
    print("Therefore X =", X)
else:
    print("The matrix is singular. can't be solved.")


Therefore X = [ 2.  1. -2.]
